
{{ if hasKey .Values.env }}
  {{ fail "The Value env has been renamed and moved to tezgpt.configEnv. Refer to https://www.tezgpt.app/docs/local/helm_chart#migrate for more information" }}
{{ end }}